// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Teachify.DAL.DVM
{
    public partial class ProviderDVM
    {
        [Key]
        public int Id { get; set; }
        [StringLength(50)]
        public string Firstname { get; set; }
        [StringLength(50)]
        public string Lastname { get; set; }
        [StringLength(50)]
        public string Nationality { get; set; }
        [StringLength(50)]
        public string Gender { get; set; }
        [StringLength(50)]
        public string Phone { get; set; }
        [StringLength(50)]
        public string Email { get; set; }
        [StringLength(50)]
        public string Education { get; set; }
        [StringLength(50)]
        public string OneLineTitle { get; set; }
        [Column(TypeName = "text")]
        public string Description { get; set; }
        [Column(TypeName = "text")]
        public string Experience { get; set; }
        [StringLength(50)]
        public string HourlyRate { get; set; }
        [StringLength(50)]
        public string CourseDomain { get; set; }
        [StringLength(50)]
        public string City { get; set; }
        [StringLength(150)]
        public string ImageUrl { get; set; }
        [StringLength(150)]
        public string LogoUrl { get; set; }
    }
}