// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Teachify.API.VM
{
    public partial class AspNetRoleClaimVM
    {
        [Key]
        public int Id { get; set; }
        [Required]
        [StringLength(450)]
        public string RoleId { get; set; }
        public string ClaimType { get; set; }
        public string ClaimValue { get; set; }

        public virtual AspNetRoleVM Role { get; set; }
    }
}