// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Teachify.Models
{
    public partial class AspNetUserRoleVM
    {
        public string UserId { get; set; }
        public string RoleId { get; set; }
    }
}