// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Teachify.Models
{
    public partial class CountryVM
    {

        public string Code { get; set; }
        public string Name { get; set; }
    }
}