// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Teachify.Models
{
    public partial class StateVM
    {
        public string Code { get; set; }
        public string Name { get; set; }
        public string CountryId { get; set; }
        public string RegionCode { get; set; }
    }
}